// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgECk_jnzdKngxBJRKF4Sq-I2mCm9xwFs',
    appId: '1:656786692910:web:f60d6065a34726ed69b8bf',
    messagingSenderId: '656786692910',
    projectId: 'egyption-foods',
    authDomain: 'egyption-foods.firebaseapp.com',
    storageBucket: 'egyption-foods.firebasestorage.app',
    measurementId: 'G-V4QWL60MR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaId_bDxK8s0l8PYrReDGFAnzZKaGZOG0',
    appId: '1:656786692910:android:a38f1fffcec1430769b8bf',
    messagingSenderId: '656786692910',
    projectId: 'egyption-foods',
    storageBucket: 'egyption-foods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8f82CGYYmrBHZJm6DIn_tUVA3ANaOoU',
    appId: '1:656786692910:ios:5e21bd6d65c555a169b8bf',
    messagingSenderId: '656786692910',
    projectId: 'egyption-foods',
    storageBucket: 'egyption-foods.firebasestorage.app',
    iosBundleId: 'com.example.egyptionFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH8f82CGYYmrBHZJm6DIn_tUVA3ANaOoU',
    appId: '1:656786692910:ios:5e21bd6d65c555a169b8bf',
    messagingSenderId: '656786692910',
    projectId: 'egyption-foods',
    storageBucket: 'egyption-foods.firebasestorage.app',
    iosBundleId: 'com.example.egyptionFoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgECk_jnzdKngxBJRKF4Sq-I2mCm9xwFs',
    appId: '1:656786692910:web:36f929fee3f67ea769b8bf',
    messagingSenderId: '656786692910',
    projectId: 'egyption-foods',
    authDomain: 'egyption-foods.firebaseapp.com',
    storageBucket: 'egyption-foods.firebasestorage.app',
    measurementId: 'G-WZKY0XQEDX',
  );
}
